// src/app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs' // <-- Import This

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // Provider se wrap kiya taaki poori app me user info mil sake
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}